version: '2'
services:
    prueba2-app:
        image: prueba2
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://prueba2-postgresql:5432/Prueba2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    prueba2-postgresql:
        extends:
            file: postgresql.yml
            service: prueba2-postgresql
